# Generated by Django 5.2.14 on 2026-05-25 09:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('succeeded', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('triggered_by', models.CharField(default='manual', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(db_index=True, max_length=120)),
                ('url', models.URLField(max_length=2000)),
                ('latest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='IRR', max_length=8)),
                ('availability_status', models.CharField(choices=[('unknown', 'Unknown'), ('in_stock', 'In stock'), ('out_of_stock', 'Out of stock')], default='unknown', max_length=20)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('crawl_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='products.product')),
            ],
            options={
                'ordering': ['website_name'],
                'unique_together': {('product', 'website_name', 'url')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('availability_status', models.CharField(choices=[('unknown', 'Unknown'), ('in_stock', 'In stock'), ('out_of_stock', 'Out of stock')], default='unknown', max_length=20)),
                ('crawled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('product_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.productsource')),
            ],
            options={
                'ordering': ['-crawled_at'],
                'indexes': [models.Index(fields=['product_source', '-crawled_at'], name='products_pr_product_691d6e_idx')],
            },
        ),
    ]
